-f scripts/rtl_files.f
vsrc/soc/bus/bus_interconnect.sv
vsrc/soc/bus/local_to_axi.sv
vsrc/soc/memory/tcm_controller.sv
vsrc/soc/memory/boot_rom.sv
vsrc/soc/common/mmio_endpoint.sv
vsrc/soc/common/sync_bits.sv
vsrc/soc/common/soc_info.sv
vsrc/soc/peripheral/timer/machine_timer.sv
vsrc/soc/peripheral/timer/general_timer.sv
vsrc/soc/peripheral/gpio/gpio.sv
vsrc/soc/peripheral/uart/uart_tx.sv
vsrc/soc/peripheral/uart/uart_rx.sv
vsrc/soc/peripheral/uart/uart.sv
vsrc/soc/interrupt/irq_controller.sv
vsrc/soc/dma/dma_engine.sv
vsrc/soc/dma/dma_regs.sv
vsrc/soc/dma/dma_controller.sv
vsrc/soc/peripheral/soc_peripherals.sv
vsrc/soc/cache/cache_port.sv
vsrc/soc/cache/cache_data_array.sv
vsrc/soc/cache/cache_meta_array.sv
vsrc/soc/cache/cache_refill.sv
vsrc/soc/cache/icache.sv
vsrc/soc/cache/dcache.sv
vsrc/soc/soc_top.sv
